version: '2'
services:

  web:
    image: ansible/awx:16.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "~/awx-docker-compose/awx_compose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "~/awx-docker-compose/awx_compose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "~/awx-docker-compose/awx_compose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "~/awx-docker-compose/awx_compose/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "~/awx-docker-compose/awx_compose/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:

  task:
    image: ansible/awx:16.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - supervisor-socket:/var/run/supervisor
      - rsyslog-socket:/var/run/awx-rsyslog/
      - rsyslog-config:/var/lib/awx/rsyslog/
      - "~/awx-docker-compose/awx_compose/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "~/awx-docker-compose/awx_compose/environment.sh:/etc/tower/conf.d/environment.sh"
      - "~/awx-docker-compose/awx_compose/credentials.py:/etc/tower/conf.d/credentials.py"
      - "~/awx-docker-compose/awx_compose/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "~/awx-docker-compose/awx_compose/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "~/awx-docker-compose/awx_compose/redis_socket:/var/run/redis/:rw"

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - pgdocker:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy:
      https_proxy:
      no_proxy:


volumes:
  pgdocker:
  awxasset:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
